server:
  port: 8190
  servlet:
    context-path: /foodorder

google:
  maps:
    api:
      key: AIzaSyDvwTDMi-cXeamefAssYo3ZmhtHXnnZO9g


spring:
#  security:
#    enabled: false
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/foodorder
    username: postgres
    password: postgres
    hikari:
      idle-timeout: 10000
      connectionTimeout: 2000
      minimumIdle: 10
      maximumPoolSize: 20
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: false
        format_sql: false
  mvc:
    hidden-method:
      filter:
        enabled: true
