insert into OWNER (name, surname, phone, email) values ('Jonh', 'Doe', '571 731 7592', 'owner@gmail.com');
insert into OWNER (name, surname, phone, email) values ('Hetty', 'Frawley', '700 457 1196', 'hfrawley1@samsung.com');

insert into CUSTOMER (name, surname, phone, email) values ('Marcin', 'Sikora', '417 595 1397', 'customer@interia.pl');
insert into CUSTOMER (name, surname, phone, email) values ('Corine', 'Dunsire', '957 408 5246', 'cdunsire1@virginia.edu');
insert into CUSTOMER (name, surname, phone, email) values ('Inga', 'McGown', '282 736 5542', 'imcgown2@vimeo.com');
insert into CUSTOMER (name, surname, phone, email) values ('Lolita', 'Sallter', '292 499 9098', 'lsallter3@mac.com');
insert into CUSTOMER (name, surname, phone, email) values ('Austin', 'Dowsey', '676 297 2107', 'adowsey4@rakuten.co.jp');
insert into CUSTOMER (name, surname, phone, email) values ('Georgeanne', 'Raoux', '929 895 7582', 'graoux5@qq.com');
insert into CUSTOMER (name, surname, phone, email) values ('Ber', 'Rosa', '807 197 0433', 'brosa6@github.com');
insert into CUSTOMER (name, surname, phone, email) values ('Carmine', 'Nevett', '158 335 3552', 'cnevett7@friendfeed.com');
insert into CUSTOMER (name, surname, phone, email) values ('Candis', 'Begg', '863 203 3419', 'cbegg8@google.cn');
insert into CUSTOMER (name, surname, phone, email) values ('Berny', 'Edworthye', '720 392 5699', 'bedworthye9@hud.gov');



insert into street (city, street) values ('Poznań', 'Adama Biedrzyckiego');
insert into street (city, street) values ('Poznań', 'Adama Kręglewskiego');
insert into street (city, street) values ('Poznań', 'Adama Mickiewicza');
insert into street (city, street) values ('Poznań', 'Adolfa Bnińskiego');
insert into street (city, street) values ('Poznań', 'Agrestowa');
insert into street (city, street) values ('Poznań', 'Akacjowa');
insert into street (city, street) values ('Poznań', 'Aleksandra Puszkina');
insert into street (city, street) values ('Poznań', 'Aleksandry Karpińskiej');
insert into street (city, street) values ('Poznań', 'Alojzego Andrzeja Łuczaka');
insert into street (city, street) values ('Poznań', 'Andaluzyjska');
insert into street (city, street) values ('Poznań', 'Andrzeja Kopy');
insert into street (city, street) values ('Poznań', 'Andrzeja Rzewuskiego');
insert into street (city, street) values ('Poznań', 'Anny Jantar');
insert into street (city, street) values ('Poznań', 'Antona Czechowa');
insert into street (city, street) values ('Poznań', 'Antoniego Babińskiego');
insert into street (city, street) values ('Poznań', 'Antoniego Pallutha');
insert into street (city, street) values ('Poznań', 'Anyżowa');
insert into street (city, street) values ('Poznań', 'Architektów');
insert into street (city, street) values ('Poznań', 'Arnolda Szylinga');
insert into street (city, street) values ('Poznań', 'Artura Marii Swinarskiego');
insert into street (city, street) values ('Poznań', 'Arystofanesa');
insert into street (city, street) values ('Poznań', 'Azaliowa');
insert into street (city, street) values ('Poznań', 'Babimojska');
insert into street (city, street) values ('Poznań', 'Bakaliowa');
insert into street (city, street) values ('Poznań', 'Barbary Lerczakówny');
insert into street (city, street) values ('Poznań', 'Barlinecka');
insert into street (city, street) values ('Poznań', 'Bartnicza');
insert into street (city, street) values ('Poznań', 'Bazyliowa');
insert into street (city, street) values ('Poznań', 'Będzińska');
insert into street (city, street) values ('Poznań', 'Bełchatowska');
insert into street (city, street) values ('Poznań', 'Berylowa');
insert into street (city, street) values ('Poznań', 'Biała');
insert into street (city, street) values ('Poznań', 'Białoborska');
insert into street (city, street) values ('Poznań', 'Biebrzańska');
insert into street (city, street) values ('Poznań', 'Bielniki');
insert into street (city, street) values ('Poznań', 'Biesiadna');
insert into street (city, street) values ('Poznań', 'bł. Marii Karłowskiej');
insert into street (city, street) values ('Poznań', 'Blacharska');
insert into street (city, street) values ('Poznań', 'Błażeja');
insert into street (city, street) values ('Poznań', 'Bluszczowa');
insert into street (city, street) values ('Poznań', 'Bobrownicka');
insert into street (city, street) values ('Poznań', 'Bocheńska');
insert into street (city, street) values ('Poznań', 'Bogumiła');
insert into street (city, street) values ('Poznań', 'Bogusza');
insert into street (city, street) values ('Poznań', 'Bohaterów II Wojny Światowej');
insert into street (city, street) values ('Poznań', 'Bolesława Chrobrego');
insert into street (city, street) values ('Poznań', 'Bolesława Krysiewicza');
insert into street (city, street) values ('Poznań', 'Bolesława Leśmiana');
insert into street (city, street) values ('Poznań', 'Bonin');
insert into street (city, street) values ('Poznań', 'Borowa');
insert into street (city, street) values ('Poznań', 'Borówki');
insert into street (city, street) values ('Poznań', 'Bożeny');
insert into street (city, street) values ('Poznań', 'Bożymira');
insert into street (city, street) values ('Poznań', 'Braniborska');
insert into street (city, street) values ('Poznań', 'Bronisława');
insert into street (city, street) values ('Poznań', 'Bronowa');
insert into street (city, street) values ('Poznań', 'Bruzdowa');
insert into street (city, street) values ('Poznań', 'Budzisława');
insert into street (city, street) values ('Poznań', 'Bukowa');
insert into street (city, street) values ('Poznań', 'Bułgarska');
insert into street (city, street) values ('Poznań', 'Bużańska');
insert into street (city, street) values ('Poznań', 'Bydgoska');
insert into street (city, street) values ('Poznań', 'Bylicowa');
insert into street (city, street) values ('Poznań', 'Ceglana');
insert into street (city, street) values ('Poznań', 'Cerekwicka');
insert into street (city, street) values ('Poznań', 'Chabrowa');
insert into street (city, street) values ('Poznań', 'Chłodna');
insert into street (city, street) values ('Poznań', 'Chochołowska');
insert into street (city, street) values ('Poznań', 'Chocimska');
insert into street (city, street) values ('Poznań', 'Chrobacka');
insert into street (city, street) values ('Poznań', 'Chwaliszewo');
insert into street (city, street) values ('Poznań', 'Ciasna');
insert into street (city, street) values ('Poznań', 'Cisowa');
insert into street (city, street) values ('Poznań', 'Conrada Drzewieckiego');
insert into street (city, street) values ('Poznań', 'Cybińska');
insert into street (city, street) values ('Poznań', 'Cyryla Ratajskiego');
insert into street (city, street) values ('Poznań', 'Czajcza');
insert into street (city, street) values ('Poznań', 'Czaplinecka');
insert into street (city, street) values ('Poznań', 'Czechosłowacka');
insert into street (city, street) values ('Poznań', 'Czekoladowa');
insert into street (city, street) values ('Poznań', 'Czempińska');
insert into street (city, street) values ('Poznań', 'Czesława Gerwela');
insert into street (city, street) values ('Poznań', 'Czesława Niemena');
insert into street (city, street) values ('Poznań', 'Cześnikowska');
insert into street (city, street) values ('Poznań', 'Dąbrówki');
insert into street (city, street) values ('Poznań', 'Dalemińska');
insert into street (city, street) values ('Poznań', 'Danuty');
insert into street (city, street) values ('Poznań', 'Dębina');
insert into street (city, street) values ('Poznań', 'Dedala');
insert into street (city, street) values ('Poznań', 'Deszczowa');
insert into street (city, street) values ('Poznań', 'Dobra');
insert into street (city, street) values ('Poznań', 'Dobrochny');
insert into street (city, street) values ('Poznań', 'Dobromiejska');
insert into street (city, street) values ('Poznań', 'Dolna Wilda');
insert into street (city, street) values ('Poznań', 'Dominikańska');
insert into street (city, street) values ('Poznań', 'Drawska');
insert into street (city, street) values ('Poznań', 'Drużynowa');
insert into street (city, street) values ('Poznań', 'Dunajecka');
insert into street (city, street) values ('Poznań', 'Dwatory');
insert into street (city, street) values ('Poznań', 'Działkowa');
insert into street (city, street) values ('Poznań', 'Działyńskich');
insert into street (city, street) values ('Poznań', 'Dzieci Wrzesińskich');
insert into street (city, street) values ('Poznań', 'Dziurawcowa');
insert into street (city, street) values ('Poznań', 'Edmunda Knolla-Kownackiego');
insert into street (city, street) values ('Poznań', 'Edwarda Dembowskiego');
insert into street (city, street) values ('Poznań', 'Elizy Orzeszkowej');
insert into street (city, street) values ('Poznań', 'Emila Zoli');
insert into street (city, street) values ('Poznań', 'Emilii Sczanieckiej');
insert into street (city, street) values ('Poznań', 'Eugeniusza Paukszty');
insert into street (city, street) values ('Poznań', 'Ewangelicka');
insert into street (city, street) values ('Poznań', 'Ewy Szelburg-Zarembiny');
insert into street (city, street) values ('Poznań', 'Feliksa Nowowiejskiego');
insert into street (city, street) values ('Poznań', 'Filarecka');
insert into street (city, street) values ('Poznań', 'Filipiny i Konstancji Studzińskich');
insert into street (city, street) values ('Poznań', 'Folwarczna');
insert into street (city, street) values ('Poznań', 'Franciszka Adamanisa');
insert into street (city, street) values ('Poznań', 'Franciszka Firlika');
insert into street (city, street) values ('Poznań', 'Franciszka Rataja');
insert into street (city, street) values ('Poznań', 'Franciszka Stróżyńskiego');
insert into street (city, street) values ('Poznań', 'Franciszka Włada');
insert into street (city, street) values ('Poznań', 'Fromborska');
insert into street (city, street) values ('Poznań', 'Fryderyka Skarbka');
insert into street (city, street) values ('Poznań', 'Gabrieli Zapolskiej');
insert into street (city, street) values ('Poznań', 'Gardowska');
insert into street (city, street) values ('Poznań', 'Gąsiorowskich');
insert into street (city, street) values ('Poznań', 'Gdyńska');
insert into street (city, street) values ('Poznań', 'Gerberowa');
insert into street (city, street) values ('Poznań', 'Gieorgija Dobrowolskiego');
insert into street (city, street) values ('Poznań', 'Gladiolowa');
insert into street (city, street) values ('Poznań', 'Glinno');
insert into street (city, street) values ('Poznań', 'Głogowska');
insert into street (city, street) values ('Poznań', 'Główna');
insert into street (city, street) values ('Poznań', 'Gołdapska');
insert into street (city, street) values ('Poznań', 'Golęczewska');
insert into street (city, street) values ('Poznań', 'Gołężycka');
insert into street (city, street) values ('Poznań', 'Górczyńska');
insert into street (city, street) values ('Poznań', 'Gorlicka');
insert into street (city, street) values ('Poznań', 'Górnicza');
insert into street (city, street) values ('Poznań', 'Gostyńska');
insert into street (city, street) values ('Poznań', 'Grąbczowska');
insert into street (city, street) values ('Poznań', 'Grabowska');
insert into street (city, street) values ('Poznań', 'Grobla');
insert into street (city, street) values ('Poznań', 'Grodnicka');
insert into street (city, street) values ('Poznań', 'Grodziska');
insert into street (city, street) values ('Poznań', 'Grudziądzka');
insert into street (city, street) values ('Poznań', 'Grunwaldzka');
insert into street (city, street) values ('Poznań', 'Gruzińska');
insert into street (city, street) values ('Poznań', 'Gustawa Herlinga-Grudzińskiego');
insert into street (city, street) values ('Poznań', 'Gwarna');
insert into street (city, street) values ('Poznań', 'Hajduczka');
insert into street (city, street) values ('Poznań', 'Halszki');
insert into street (city, street) values ('Poznań', 'Hanny Januszewskiej');
insert into street (city, street) values ('Poznań', 'Harcerska');
insert into street (city, street) values ('Poznań', 'Heliodora Święcickiego');
insert into street (city, street) values ('Poznań', 'Henryka Derwicha');
insert into street (city, street) values ('Poznań', 'Henryka Kowalówki');
insert into street (city, street) values ('Poznań', 'Henryka Ułaszyna');
insert into street (city, street) values ('Poznań', 'Herbowa');
insert into street (city, street) values ('Poznań', 'Hetmańskie');
insert into street (city, street) values ('Poznań', 'Honoriusza Balzaka');
insert into street (city, street) values ('Poznań', 'Hrubieszowska');
insert into street (city, street) values ('Poznań', 'Huby Moraskie');
insert into street (city, street) values ('Poznań', 'Ignacego Dobrogojskiego');
insert into street (city, street) values ('Poznań', 'Ignacego Krasickiego');
insert into street (city, street) values ('Poznań', 'Ignacego Paderewskiego');
insert into street (city, street) values ('Poznań', 'Inflancka');
insert into street (city, street) values ('Poznań', 'Ireneusza Wierzejewskiego');
insert into street (city, street) values ('Poznań', 'Ireny Sendlerowej');
insert into street (city, street) values ('Poznań', 'Izbicka');
insert into street (city, street) values ('Poznań', 'Jacka Kaczmarskiego');
insert into street (city, street) values ('Poznań', 'Jacka Rychlewskiego');
insert into street (city, street) values ('Poznań', 'Jagodowa');
insert into street (city, street) values ('Poznań', 'Jana Baptysty Quadro');
insert into street (city, street) values ('Poznań', 'Jana Czekanowskiego');
insert into street (city, street) values ('Poznań', 'Jana Karskiego');
insert into street (city, street) values ('Poznań', 'Jana Keplera');
insert into street (city, street) values ('Poznań', 'Jana Kochanowskiego');
insert into street (city, street) values ('Poznań', 'Jana Ostroroga');
insert into street (city, street) values ('Poznań', 'Jana Piekałkiewicza');
insert into street (city, street) values ('Poznań', 'Jana Piwnika');
insert into street (city, street) values ('Poznań', 'Jana Stryczyńskiego');
insert into street (city, street) values ('Poznań', 'Jana Umińskiego');
insert into street (city, street) values ('Poznań', 'Jana Wojkiewicza');
insert into street (city, street) values ('Poznań', 'Janiny Porazińskiej');
insert into street (city, street) values ('Poznań', 'Janowo');
insert into street (city, street) values ('Poznań', 'Janusza Korczaka');
insert into street (city, street) values ('Poznań', 'Jarmużowa');
insert into street (city, street) values ('Poznań', 'Jaromira');
insert into street (city, street) values ('Poznań', 'Jarosława Maciejewskiego');
insert into street (city, street) values ('Poznań', 'Jaskółcza');
insert into street (city, street) values ('Poznań', 'Jasna Rola');
insert into street (city, street) values ('Poznań', 'Jaspisowa');
insert into street (city, street) values ('Poznań', 'Jedlicka');
insert into street (city, street) values ('Poznań', 'Jelitkowska');
insert into street (city, street) values ('Poznań', 'Jerzego Bajana');
insert into street (city, street) values ('Poznań', 'Jesionowa');
insert into street (city, street) values ('Poznań', 'rynek Jeżycki');
insert into street (city, street) values ('Poznań', 'Joachima Lelewela');
insert into street (city, street) values ('Poznań', 'Józefa Edwarda Grobelnego');
insert into street (city, street) values ('Poznań', 'Józefa Hallera');
insert into street (city, street) values ('Poznań', 'Józefa Kościelskiego');
insert into street (city, street) values ('Poznań', 'Józefa Przesławskiego');
insert into street (city, street) values ('Poznań', 'Józefa Rogalińskiego');
insert into street (city, street) values ('Poznań', 'Józefa Sowińskiego');
insert into street (city, street) values ('Poznań', 'Jugosłowiańska');
insert into street (city, street) values ('Poznań', 'Julii i Antoniego Wojkowskich');
insert into street (city, street) values ('Poznań', 'Juliusza Osterwy');
insert into street (city, street) values ('Poznań', 'Jutrosińska');
insert into street (city, street) values ('Poznań', 'Kabaczkowa');
insert into street (city, street) values ('Poznań', 'Kacza');
insert into street (city, street) values ('Poznań', 'Kamienicka');
insert into street (city, street) values ('Poznań', 'Kamieńska');
insert into street (city, street) values ('Poznań', 'Kanclerska');
insert into street (city, street) values ('Poznań', 'Karkonoska');
insert into street (city, street) values ('Poznań', 'Karmelowa');
insert into street (city, street) values ('Poznań', 'Karola Bunscha');
insert into street (city, street) values ('Poznań', 'Karpacka');
insert into street (city, street) values ('Poznań', 'Karsińska');
insert into street (city, street) values ('Poznań', 'Karwieńska');
insert into street (city, street) values ('Poznań', 'Katowicka');
insert into street (city, street) values ('Poznań', 'Kazimierza Brandysa');
insert into street (city, street) values ('Poznań', 'Kazimierza Drewnowskiego');
insert into street (city, street) values ('Poznań', 'Kazimierza Nowakowskiego');
insert into street (city, street) values ('Poznań', 'Kazimierza Spornego');
insert into street (city, street) values ('Poznań', 'Kazimierza Tymienieckiego');
insert into street (city, street) values ('Poznań', 'Kielecka');
insert into street (city, street) values ('Poznań', 'Kirchholmska');
insert into street (city, street) values ('Poznań', 'Klaudyny Potockiej');
insert into street (city, street) values ('Poznań', 'Klimatyczna');
insert into street (city, street) values ('Poznań', 'Klinkierowa');
insert into street (city, street) values ('Poznań', 'Kłońska');
insert into street (city, street) values ('Poznań', 'Knyszyn');
insert into street (city, street) values ('Poznań', 'Kocankowa');
insert into street (city, street) values ('Poznań', 'Kokosowa');
insert into street (city, street) values ('Poznań', 'Kolska');
insert into street (city, street) values ('Poznań', 'Komornicka');
insert into street (city, street) values ('Poznań', 'Konarzewska');
insert into street (city, street) values ('Poznań', 'Konstantego Ildefonsa Gałczyńskiego');
insert into street (city, street) values ('Poznań', 'Konwaliowa');
insert into street (city, street) values ('Poznań', 'Kopciuszka');
insert into street (city, street) values ('Poznań', 'Korczyńska');
insert into street (city, street) values ('Poznań', 'Kórnicka');
insert into street (city, street) values ('Poznań', 'Koronna');
insert into street (city, street) values ('Poznań', 'Kosiarzy');
insert into street (city, street) values ('Poznań', 'Kostrzyńska');
insert into street (city, street) values ('Poznań', 'Koszalińska');
insert into street (city, street) values ('Poznań', 'Kozia');
insert into street (city, street) values ('Poznań', 'Koźmińska');
insert into street (city, street) values ('Poznań', 'Krajenecka');
insert into street (city, street) values ('Poznań', 'Krasnoludków');
insert into street (city, street) values ('Poznań', 'Krokusowa');
insert into street (city, street) values ('Poznań', 'Królewny Śnieżki');
insert into street (city, street) values ('Poznań', 'Krucza');
insert into street (city, street) values ('Poznań', 'Krynicka');
insert into street (city, street) values ('Poznań', 'Kryształowa');
insert into street (city, street) values ('Poznań', 'Krzysztofa Kamila Baczyńskiego');
insert into street (city, street) values ('Poznań', 'Krzywa');
insert into street (city, street) values ('Poznań', 'Krzyżowa');
insert into street (city, street) values ('Poznań', 'ks. Jerzego Popiełuszki');
insert into street (city, street) values ('Poznań', 'ks. Stanisława Brzóski');
insert into street (city, street) values ('Poznań', 'ks.Tomasza Maćkowiaka');
insert into street (city, street) values ('Poznań', 'Ku Dębinie');
insert into street (city, street) values ('Poznań', 'Kukułcza');
insert into street (city, street) values ('Poznań', 'Kurlandzka');
insert into street (city, street) values ('Poznań', 'Kwidzyńska');
insert into street (city, street) values ('Poznań', 'Łabiszyńska');
insert into street (city, street) values ('Poznań', 'Łacina');
insert into street (city, street) values ('Poznań', 'Łanowa');
insert into street (city, street) values ('Poznań', 'Laudańska');
insert into street (city, street) values ('Poznań', 'Lawendowa');
insert into street (city, street) values ('Poznań', 'Łebska');
insert into street (city, street) values ('Poznań', 'Lechicka');
insert into street (city, street) values ('Poznań', 'Lednicka');
insert into street (city, street) values ('Poznań', 'Leopolda Okulickiego');
insert into street (city, street) values ('Poznań', 'Leska');
insert into street (city, street) values ('Poznań', 'Leśników');
insert into street (city, street) values ('Poznań', 'Letniskowa');
insert into street (city, street) values ('Poznań', 'Lidzbarska');
insert into street (city, street) values ('Poznań', 'Liliowa');
insert into street (city, street) values ('Poznań', 'Liryczna');
insert into street (city, street) values ('Poznań', 'Listopadowa');
insert into street (city, street) values ('Poznań', 'Litewska');
insert into street (city, street) values ('Poznań', 'Longinusa Podbipięty');
insert into street (city, street) values ('Poznań', 'Łosiowa');
insert into street (city, street) values ('Poznań', 'Łotewska');
insert into street (city, street) values ('Poznań', 'Łozowa');
insert into street (city, street) values ('Poznań', 'Lubczykowa');
insert into street (city, street) values ('Poznań', 'Lubiatowska');
insert into street (city, street) values ('Poznań', 'Lubowska');
insert into street (city, street) values ('Poznań', 'Łucji Danielewskiej');
insert into street (city, street) values ('Poznań', 'Łuczanowska');
insert into street (city, street) values ('Poznań', 'Ludwika Krzywickiego');
insert into street (city, street) values ('Poznań', 'Ludwika Zamenhofa');
insert into street (city, street) values ('Poznań', 'Ługańska');
insert into street (city, street) values ('Poznań', 'Lwa Tołstoja');
insert into street (city, street) values ('Poznań', 'Łysogórska');
insert into street (city, street) values ('Poznań', 'Macieja Palacza');
insert into street (city, street) values ('Poznań', 'Magnacka');
insert into street (city, street) values ('Poznań', 'Majowa');
insert into street (city, street) values ('Poznań', 'Maków Polnych');
insert into street (city, street) values ('Poznań', 'Malachitowa');
insert into street (city, street) values ('Poznań', 'Malechowska');
insert into street (city, street) values ('Poznań', 'Małopolska');
insert into street (city, street) values ('Poznań', 'Marcelin Fort VII');
insert into street (city, street) values ('Poznań', 'Marcina Rożka');
insert into street (city, street) values ('Poznań', 'Margonińska');
insert into street (city, street) values ('Poznań', 'Marianny Marszałkowskiej-Kaniewskiej');
insert into street (city, street) values ('Poznań', 'Marii Dulębianki');
insert into street (city, street) values ('Poznań', 'Marii i Lecha Kaczyńskich');
insert into street (city, street) values ('Poznań', 'Marii Rodziewiczówny');
insert into street (city, street) values ('Poznań', 'Marii Szembekowej');
insert into street (city, street) values ('Poznań', 'Marii Wicherkiewicz');
insert into street (city, street) values ('Poznań', 'Marzanny');
insert into street (city, street) values ('Poznań', 'Masztowa');
insert into street (city, street) values ('Poznań', 'Mazowiecka');
insert into street (city, street) values ('Poznań', 'Mewy');
insert into street (city, street) values ('Poznań', 'Michaiła Bułhakowa');
insert into street (city, street) values ('Poznań', 'Michała Bałuckiego');
insert into street (city, street) values ('Poznań', 'Michała Tomiaka');
insert into street (city, street) values ('Poznań', 'Michałowo');
insert into street (city, street) values ('Poznań', 'Miechowska');
insert into street (city, street) values ('Poznań', 'Mieczysławy Ruxerówny');
insert into street (city, street) values ('Poznań', 'Międzychodzka');
insert into street (city, street) values ('Poznań', 'Międzymoście');
insert into street (city, street) values ('Poznań', 'Mikołaja Dobrzyckiego');
insert into street (city, street) values ('Poznań', 'Mikołaja Rudnickiego');
insert into street (city, street) values ('Poznań', 'Mikołowska');
insert into street (city, street) values ('Poznań', 'Miłowita');
insert into street (city, street) values ('Poznań', 'Miodowa');
insert into street (city, street) values ('Poznań', 'Mirosławiecka');
insert into street (city, street) values ('Poznań', 'Młyńska');
insert into street (city, street) values ('Poznań', 'Modrakowa');
insert into street (city, street) values ('Poznań', 'Mogileńska');
insert into street (city, street) values ('Poznań', 'Morawska');
insert into street (city, street) values ('Poznań', 'Morska');
insert into street (city, street) values ('Poznań', 'Morwowa');
insert into street (city, street) values ('Poznań', 'Mrzeżyńska');
insert into street (city, street) values ('Poznań', 'Murna');
insert into street (city, street) values ('Poznań', 'Muszyńska');
insert into street (city, street) values ('Poznań', 'Na Murawie');
insert into street (city, street) values ('Poznań', 'Na Stoku');
insert into street (city, street) values ('Poznań', 'Na Uboczu');
insert into street (city, street) values ('Poznań', 'Nad Potokiem');
insert into street (city, street) values ('Poznań', 'Nad Seganką');
insert into street (city, street) values ('Poznań', 'Nad Starynką');
insert into street (city, street) values ('Poznań', 'Nakielska');
insert into street (city, street) values ('Poznań', 'Napoleońska');
insert into street (city, street) values ('Poznań', 'Narcyzowa');
insert into street (city, street) values ('Poznań', 'Nektarynkowa');
insert into street (city, street) values ('Poznań', 'Niecała');
insert into street (city, street) values ('Poznań', 'Niepodległości');
insert into street (city, street) values ('Poznań', 'Nikołaja Gogola');
insert into street (city, street) values ('Poznań', 'Nizinna');
insert into street (city, street) values ('Poznań', 'Nostrzykowa');
insert into street (city, street) values ('Poznań', 'Nowosolska');
insert into street (city, street) values ('Poznań', 'Nowy Świat');
insert into street (city, street) values ('Poznań', 'o. Honoriusza Kowalczyka');
insert into street (city, street) values ('Poznań', 'Obrońców Ukrainy 2022');
insert into street (city, street) values ('Poznań', 'Obrzeże');
insert into street (city, street) values ('Poznań', 'Obrzycka');
insert into street (city, street) values ('Poznań', 'Ogrodowa');
insert into street (city, street) values ('Poznań', 'Okólna');
insert into street (city, street) values ('Poznań', 'Okopowa');
insert into street (city, street) values ('Poznań', 'Oleszycka');
insert into street (city, street) values ('Poznań', 'Olimpijska');
insert into street (city, street) values ('Poznań', 'Oliwska');
insert into street (city, street) values ('Poznań', 'Opalenicka');
insert into street (city, street) values ('Poznań', 'Opawska');
insert into street (city, street) values ('Poznań', 'Opoczyńska');
insert into street (city, street) values ('Poznań', 'Orląt');
insert into street (city, street) values ('Poznań', 'Ornecka');
insert into street (city, street) values ('Poznań', 'Orzechowa');
insert into street (city, street) values ('Poznań', 'Ostródzka');
insert into street (city, street) values ('Poznań', 'Ostrówek');
insert into street (city, street) values ('Poznań', 'Ostrzeszowska');
insert into street (city, street) values ('Poznań', 'Owidiusza');
insert into street (city, street) values ('Poznań', 'Owsiana');
insert into street (city, street) values ('Poznań', 'Ozimina');
insert into street (city, street) values ('Poznań', 'Pana Twardowskiego');
insert into street (city, street) values ('Poznań', 'Papuszy');
insert into street (city, street) values ('Poznań', 'Pasieka');
insert into street (city, street) values ('Poznań', 'Pawła Cymsa');
insert into street (city, street) values ('Poznań', 'Pawła Zołotowa');
insert into street (city, street) values ('Poznań', 'Pelplińska');
insert into street (city, street) values ('Poznań', 'Petuniowa');
insert into street (city, street) values ('Poznań', 'Piaśnicka');
insert into street (city, street) values ('Poznań', 'Piastowskie');
insert into street (city, street) values ('Poznań', 'Pilicka');
insert into street (city, street) values ('Poznań', 'Pińczowska');
insert into street (city, street) values ('Poznań', 'Pionierska');
insert into street (city, street) values ('Poznań', 'Piotrowska');
insert into street (city, street) values ('Poznań', 'Plac Pomorski');
insert into street (city, street) values ('Poznań', 'Plauta');
insert into street (city, street) values ('Poznań', 'Pniewska');
insert into street (city, street) values ('Poznań', 'Pochyła');
insert into street (city, street) values ('Poznań', 'Podbiałowa');
insert into street (city, street) values ('Poznań', 'Podjaryszki');
insert into street (city, street) values ('Poznań', 'Podlaska');
insert into street (city, street) values ('Poznań', 'Podmiejska');
insert into street (city, street) values ('Poznań', 'Pogodna');
insert into street (city, street) values ('Poznań', 'Połabska');
insert into street (city, street) values ('Poznań', 'Polanicka');
insert into street (city, street) values ('Poznań', 'Poleska');
insert into street (city, street) values ('Poznań', 'Policka');
insert into street (city, street) values ('Poznań', 'Polna');
insert into street (city, street) values ('Poznań', 'Pomidorowa');
insert into street (city, street) values ('Poznań', 'Popiela');
insert into street (city, street) values ('Poznań', 'Popradzka');
insert into street (city, street) values ('Poznań', 'Poronińska');
insert into street (city, street) values ('Poznań', 'Poświata');
insert into street (city, street) values ('Poznań', 'Powozowa');
insert into street (city, street) values ('Poznań', 'Pozdawnicka');
insert into street (city, street) values ('Poznań', 'Poznańskie Sady');
insert into street (city, street) values ('Poznań', 'Prabucka');
insert into street (city, street) values ('Poznań', 'Proszowicka');
insert into street (city, street) values ('Poznań', 'Pruszkowska');
insert into street (city, street) values ('Poznań', 'Prymasa Augusta Hlonda');
insert into street (city, street) values ('Poznań', 'Przedwiośnia');
insert into street (city, street) values ('Poznań', 'Przełom');
insert into street (city, street) values ('Poznań', 'Przemyska');
insert into street (city, street) values ('Poznań', 'Przesmyk');
insert into street (city, street) values ('Poznań', 'Przy Autostradzie');
insert into street (city, street) values ('Poznań', 'Przy Lotnisku');
insert into street (city, street) values ('Poznań', 'Przylaszczkowa');
insert into street (city, street) values ('Poznań', 'Przytulna');
insert into street (city, street) values ('Poznań', 'Pszczelna');
insert into street (city, street) values ('Poznań', 'Pułtuska');
insert into street (city, street) values ('Poznań', 'Pyrzyczańska');
insert into street (city, street) values ('Poznań', 'Rabina Akivy Egera');
insert into street (city, street) values ('Poznań', 'Radomska');
insert into street (city, street) values ('Poznań', 'Radyńska');
insert into street (city, street) values ('Poznań', 'Radziwoja');
insert into street (city, street) values ('Poznań', 'Rataje');
insert into street (city, street) values ('Poznań', 'Rdestowa');
insert into street (city, street) values ('Poznań', 'Redarowska');
insert into street (city, street) values ('Poznań', 'Rewalska');
insert into street (city, street) values ('Poznań', 'Robocza');
insert into street (city, street) values ('Poznań', 'Rodawska');
insert into street (city, street) values ('Poznań', 'Rokity');
insert into street (city, street) values ('Poznań', 'Romana Brandstaettera');
insert into street (city, street) values ('Poznań', 'Romana Drewsa');
insert into street (city, street) values ('Poznań', 'Romana Wilhelmiego');
insert into street (city, street) values ('Poznań', 'Romualda Traugutta');
insert into street (city, street) values ('Poznań', 'Roślinna');
insert into street (city, street) values ('Poznań', 'Roztocka');
insert into street (city, street) values ('Poznań', 'Rubież');
insert into street (city, street) values ('Poznań', 'Ruczajowa');
insert into street (city, street) values ('Poznań', 'Rumiankowa');
insert into street (city, street) values ('Poznań', 'Ruska');
insert into street (city, street) values ('Poznań', 'Rybaki');
insert into street (city, street) values ('Poznań', 'Rymanowska');
insert into street (city, street) values ('Poznań', 'Rypińska');
insert into street (city, street) values ('Poznań', 'Ryszarda Berwińskiego');
insert into street (city, street) values ('Poznań', 'Rzepińska');
insert into street (city, street) values ('Poznań', 'Rzodkiewkowa');
insert into street (city, street) values ('Poznań', 'Sadnicka');
insert into street (city, street) values ('Poznań', 'Sandomierska');
insert into street (city, street) values ('Poznań', 'Saperska');
insert into street (city, street) values ('Poznań', 'Sarmacka');
insert into street (city, street) values ('Poznań', 'Selerowa');
insert into street (city, street) values ('Poznań', 'Sępia');
insert into street (city, street) values ('Poznań', 'Serafitek');
insert into street (city, street) values ('Poznań', 'Siedliskowa');
insert into street (city, street) values ('Poznań', 'Sielawy');
insert into street (city, street) values ('Poznań', 'Sieradzka');
insert into street (city, street) values ('Poznań', 'Silniki');
insert into street (city, street) values ('Poznań', 'Skarszewska');
insert into street (city, street) values ('Poznań', 'Skawińska');
insert into street (city, street) values ('Poznań', 'Skotarska');
insert into street (city, street) values ('Poznań', 'Skromna');
insert into street (city, street) values ('Poznań', 'Skrzydlata');
insert into street (city, street) values ('Poznań', 'Sławomira');
insert into street (city, street) values ('Poznań', 'Ślężańska');
insert into street (city, street) values ('Poznań', 'Śliwkowa');
insert into street (city, street) values ('Poznań', 'Słowiańskie');
insert into street (city, street) values ('Poznań', 'Słupecka');
insert into street (city, street) values ('Poznań', 'Ślusarska');
insert into street (city, street) values ('Poznań', 'Smoleńska');
insert into street (city, street) values ('Poznań', 'Śnieżna');
insert into street (city, street) values ('Poznań', 'Sobiesława');
insert into street (city, street) values ('Poznań', 'Sokoła');
insert into street (city, street) values ('Poznań', 'Sołtysia');
insert into street (city, street) values ('Poznań', 'Soroki');
insert into street (city, street) values ('Poznań', 'Spadzista');
insert into street (city, street) values ('Poznań', 'Spławie');
insert into street (city, street) values ('Poznań', 'Sporna');
insert into street (city, street) values ('Poznań', 'rynek Śródecki');
insert into street (city, street) values ('Poznań', 'Stanisława Barańczaka');
insert into street (city, street) values ('Poznań', 'Stanisława Broniewskiego');
insert into street (city, street) values ('Poznań', 'Stanisława Jachowicza');
insert into street (city, street) values ('Poznań', 'Stanisława Karwowskiego');
insert into street (city, street) values ('Poznań', 'Stanisława Knapowskiego');
insert into street (city, street) values ('Poznań', 'Stanisława Matyi');
insert into street (city, street) values ('Poznań', 'Stanisława Nowakowskiego');
insert into street (city, street) values ('Poznań', 'Stanisława Pawłowskiego');
insert into street (city, street) values ('Poznań', 'Stanisława Staszica');
insert into street (city, street) values ('Poznań', 'Stanisława Taczaka');
insert into street (city, street) values ('Poznań', 'Stanisława Wiechowicza');
insert into street (city, street) values ('Poznań', 'Stare Żegrze');
insert into street (city, street) values ('Poznań', 'Starołęcka');
insert into street (city, street) values ('Poznań', 'Starowiejska');
insert into street (city, street) values ('Poznań', 'Stefana Batorego');
insert into street (city, street) values ('Poznań', 'Stefana Grota-Roweckiego');
insert into street (city, street) values ('Poznań', 'Stefana Kisielewskiego');
insert into street (city, street) values ('Poznań', 'Stefana Vrtela-Wierczyńskiego');
insert into street (city, street) values ('Poznań', 'Stefanii Wojtulanis-Karpińskiej');
insert into street (city, street) values ('Poznań', 'Sterowa');
insert into street (city, street) values ('Poznań', 'Storczykowa');
insert into street (city, street) values ('Poznań', 'Strzałkowska');
insert into street (city, street) values ('Poznań', 'Strzecha');
insert into street (city, street) values ('Poznań', 'Studzienna');
insert into street (city, street) values ('Poznań', 'Sulechowska');
insert into street (city, street) values ('Poznań', 'Sułkowicka');
insert into street (city, street) values ('Poznań', 'św. Floriana');
insert into street (city, street) values ('Poznań', 'św. Kingi');
insert into street (city, street) values ('Poznań', 'św. Marii Magdaleny');
insert into street (city, street) values ('Poznań', 'Swantibora');
insert into street (city, street) values ('Poznań', 'Świątniczki');
insert into street (city, street) values ('Poznań', 'Światowida');
insert into street (city, street) values ('Poznań', 'Świerzawska');
insert into street (city, street) values ('Poznań', 'Świętochny');
insert into street (city, street) values ('Poznań', 'Świętojańska');
insert into street (city, street) values ('Poznań', 'Swoboda');
insert into street (city, street) values ('Poznań', 'Sycowska');
insert into street (city, street) values ('Poznań', 'Synów Pułku');
insert into street (city, street) values ('Poznań', 'Szafranowa');
insert into street (city, street) values ('Poznań', 'Szamocińska');
insert into street (city, street) values ('Poznań', 'Szantowa');
insert into street (city, street) values ('Poznań', 'Szczęśliwa');
insert into street (city, street) values ('Poznań', 'Szczytnicka');
insert into street (city, street) values ('Poznań', 'Szelągowska');
insert into street (city, street) values ('Poznań', 'Szmaragdowa');
insert into street (city, street) values ('Poznań', 'Szparagowa');
insert into street (city, street) values ('Poznań', 'Szpitalna');
insert into street (city, street) values ('Poznań', 'Szwajcarska');
insert into street (city, street) values ('Poznań', 'Szydłowiecka');
insert into street (city, street) values ('Poznań', 'Szymborska');
insert into street (city, street) values ('Poznań', 'Tadeusza Mikke');
insert into street (city, street) values ('Poznań', 'Tadeusza Szeligowskiego');
insert into street (city, street) values ('Poznań', 'Tajnej Organizacji Nauczycielskiej');
insert into street (city, street) values ('Poznań', 'Tczewska');
insert into street (city, street) values ('Poznań', 'Teodora Łagody');
insert into street (city, street) values ('Poznań', 'Teodora Tyca');
insert into street (city, street) values ('Poznań', 'Ternicka');
insert into street (city, street) values ('Poznań', 'Tomasza Zana');
insert into street (city, street) values ('Poznań', 'Tony Halika');
insert into street (city, street) values ('Poznań', 'Towarowa');
insert into street (city, street) values ('Poznań', 'Trocka');
insert into street (city, street) values ('Poznań', 'Truskawiecka');
insert into street (city, street) values ('Poznań', 'Trzech Tramwajarek');
insert into street (city, street) values ('Poznań', 'Tulipanowa');
insert into street (city, street) values ('Poznań', 'Turniowa');
insert into street (city, street) values ('Poznań', 'Tyniecka');
insert into street (city, street) values ('Poznań', 'Tyska');
insert into street (city, street) values ('Poznań', 'Ułańska');
insert into street (city, street) values ('Poznań', 'Urbanowska');
insert into street (city, street) values ('Poznań', 'Urszulanek');
insert into street (city, street) values ('Poznań', 'Urwista');
insert into street (city, street) values ('Poznań', 'Wacława Kopydłowskiego i Leona Stróżczyńskiego');
insert into street (city, street) values ('Poznań', 'Wadowicka');
insert into street (city, street) values ('Poznań', 'Wągrowiecka');
insert into street (city, street) values ('Poznań', 'Wandy Modlibowskiej');
insert into street (city, street) values ('Poznań', 'Warmińska');
insert into street (city, street) values ('Poznań', 'Warpińska');
insert into street (city, street) values ('Poznań', 'Wąwozowa');
insert into street (city, street) values ('Poznań', 'Wdzięczna');
insert into street (city, street) values ('Poznań', 'Węgorzewska');
insert into street (city, street) values ('Poznań', 'Wiatraczna');
insert into street (city, street) values ('Poznań', 'Wichrowe Wzgórze');
insert into street (city, street) values ('Poznań', 'Widłakowa');
insert into street (city, street) values ('Poznań', 'Wielichowska');
insert into street (city, street) values ('Poznań', 'Wielkopolska');
insert into street (city, street) values ('Poznań', 'Wieluńska');
insert into street (city, street) values ('Poznań', 'Wiesławy');
insert into street (city, street) values ('Poznań', 'Wiewiórcza');
insert into street (city, street) values ('Poznań', 'Więzowska');
insert into street (city, street) values ('Poznań', 'Wilcza');
insert into street (city, street) values ('Poznań', 'Wileńska');
insert into street (city, street) values ('Poznań', 'Wilkońskich');
insert into street (city, street) values ('Poznań', 'Wincentego Różańskiego');
insert into street (city, street) values ('Poznań', 'Winiarska');
insert into street (city, street) values ('Poznań', 'Winna');
insert into street (city, street) values ('Poznań', 'Wiślana');
insert into street (city, street) values ('Poznań', 'Wiśniowa');
insert into street (city, street) values ('Poznań', 'Witnicka');
insert into street (city, street) values ('Poznań', 'Władysława Bełzy');
insert into street (city, street) values ('Poznań', 'Władysława Jagiełły');
insert into street (city, street) values ('Poznań', 'Władysława Kozłowskiego');
insert into street (city, street) values ('Poznań', 'Władysława Syrokomli');
insert into street (city, street) values ('Poznań', 'Władysława Zamoyskiego');
insert into street (city, street) values ('Poznań', 'Włodarska');
insert into street (city, street) values ('Poznań', 'Wojciecha Bąka');
insert into street (city, street) values ('Poznań', 'Wojciecha Cybulskiego');
insert into street (city, street) values ('Poznań', 'Wojciecha Skowrońskiego');
insert into street (city, street) values ('Poznań', 'Wolbromska');
insert into street (city, street) values ('Poznań', 'Wołkowyska');
insert into street (city, street) values ('Poznań', 'Wolnica');
insert into street (city, street) values ('Poznań', 'Woźna');
insert into street (city, street) values ('Poznań', 'Wronczyńska');
insert into street (city, street) values ('Poznań', 'Wrotyczowa');
insert into street (city, street) values ('Poznań', 'Wszechnicy Piastowskiej');
insert into street (city, street) values ('Poznań', 'Wygon');
insert into street (city, street) values ('Poznań', 'Wyłom');
insert into street (city, street) values ('Poznań', 'Wyżyny');
insert into street (city, street) values ('Poznań', 'Xawerego Dunikowskiego');
insert into street (city, street) values ('Poznań', 'Za Cybiną');
insert into street (city, street) values ('Poznań', 'Zachodnia');
insert into street (city, street) values ('Poznań', 'Żagańska');
insert into street (city, street) values ('Poznań', 'Zagonowa');
insert into street (city, street) values ('Poznań', 'Zakopiańska');
insert into street (city, street) values ('Poznań', 'Zambrowska');
insert into street (city, street) values ('Poznań', 'Zamknięta');
insert into street (city, street) values ('Poznań', 'Zawady');
insert into street (city, street) values ('Poznań', 'Zbąszyńska');
insert into street (city, street) values ('Poznań', 'Zbigniewa Burzyńskiego');
insert into street (city, street) values ('Poznań', 'Zdobywców Monte Cassino');
insert into street (city, street) values ('Poznań', 'Zdziechowska');
insert into street (city, street) values ('Poznań', 'Zdzisławy');
insert into street (city, street) values ('Poznań', 'Zenona Kosidowskiego');
insert into street (city, street) values ('Poznań', 'Zgoda');
insert into street (city, street) values ('Poznań', 'Ziarnista');
insert into street (city, street) values ('Poznań', 'Ziemska');
insert into street (city, street) values ('Poznań', 'Zjazd');
insert into street (city, street) values ('Poznań', 'Złocieniecka');
insert into street (city, street) values ('Poznań', 'Żmigrodzka');
insert into street (city, street) values ('Poznań', 'Żniwna');
insert into street (city, street) values ('Poznań', 'Zodiakowa');
insert into street (city, street) values ('Poznań', 'Żołnierzy Lenino');
insert into street (city, street) values ('Poznań', 'Żołnierzy Wyklętych');
insert into street (city, street) values ('Poznań', 'Żorska');
insert into street (city, street) values ('Poznań', 'Żurawinowa');
insert into street (city, street) values ('Poznań', 'Zwierzyniecka');
insert into street (city, street) values ('Poznań', 'Zwrotnicza');
insert into street (city, street) values ('Poznań', 'Zygmunta Starego');
insert into street (city, street) values ('Poznań', 'Zygmunta Wojciechowskiego');
insert into street (city, street) values ('Poznań', 'Zygmunta Żuraszka');


insert into address (country, city, street, building_number) values ('Polska', 'Poznań', 'Spadzista','5');
insert into address (country, city, street, building_number) values ('Polska', 'Poznań', 'Adama Mickiewicza','25');
insert into address (country, city, street, building_number) values ('Polska', 'Poznań', 'Altanowa','15');
insert into address (country, city, street, building_number) values ('Polska', 'Poznań', 'Bernardyński','5');
insert into address (country, city, street, building_number) values ('Polska', 'Poznań', 'Polna','19');
insert into address (country, city, street, building_number) values ('Polska', 'Poznań', 'Chodzieska','4');
insert into address (country, city, street, building_number) values ('Polska', 'Poznań', 'Dereniowa','5');
insert into address (country, city, street, building_number) values ('Polska', 'Poznań', 'Energetyczna','5');
insert into address (country, city, street, building_number) values ('Polska', 'Poznań', 'Floksowa','5');
insert into address (country, city, street, building_number) values ('Polska', 'Poznań', 'Geodetów','5');
insert into address (country, city, street, building_number) values ('Polska', 'Poznań', 'Heleny Rzepeckiej','5');
insert into address (country, city, street, building_number) values ('Polska', 'Poznań', 'Ignacego Krasickiego','9');


insert into restaurant (name, phone, email, address_id, owner_id) values ('Szybka Picka', '970 540 3647', 'picka@t-online.de', '1', '1');
insert into restaurant (name, phone, email, address_id, owner_id) values ('Smaczne Domowe', '973 794 9792', 'smaczneDomowe@cbc.ca', '3 ', '1');
insert into restaurant (name, phone, email, address_id, owner_id) values ('Bar Bar', '859 766 0860', 'tanieSzamanie@dot.gov', '5', '1');
insert into restaurant (name, phone, email, address_id, owner_id) values ('Vifon-san', '621 301 6838', 'vi-fon@mac.com', '8', '1');
insert into restaurant (name, phone, email, address_id, owner_id) values ('Kurczaki-ziemniaki', '307 373 0225', 'kotelt@accuweather.com', '9', '2');
insert into restaurant (name, phone, email, address_id, owner_id) values ('Jadlodajnia', '307 123 0225', 'jadlo@accuweather.com', '10', '1');


insert into restaurant_street (restaurant_id, street_id) values (1,1);
insert into restaurant_street (restaurant_id, street_id) values (1,2);
insert into restaurant_street (restaurant_id, street_id) values (1,4);
insert into restaurant_street (restaurant_id, street_id) values (6,2);
insert into restaurant_street (restaurant_id, street_id) values (1,6);
insert into restaurant_street (restaurant_id, street_id) values (1,7);
insert into restaurant_street (restaurant_id, street_id) values (1,9);
insert into restaurant_street (restaurant_id, street_id) values (1,12);
insert into restaurant_street (restaurant_id, street_id) values (1,2);
insert into restaurant_street (restaurant_id, street_id) values (1,3);
insert into restaurant_street (restaurant_id, street_id) values (2,4);
insert into restaurant_street (restaurant_id, street_id) values (2,5);
insert into restaurant_street (restaurant_id, street_id) values (2,14);
insert into restaurant_street (restaurant_id, street_id) values (2,3);
insert into restaurant_street (restaurant_id, street_id) values (2,6);
insert into restaurant_street (restaurant_id, street_id) values (2,4);
insert into restaurant_street (restaurant_id, street_id) values (2,5);
insert into restaurant_street (restaurant_id, street_id) values (2,6);
insert into restaurant_street (restaurant_id, street_id) values (2,7);
insert into restaurant_street (restaurant_id, street_id) values (2,8);
insert into restaurant_street (restaurant_id, street_id) values (3,1);
insert into restaurant_street (restaurant_id, street_id) values (3,2);
insert into restaurant_street (restaurant_id, street_id) values (3,3);
insert into restaurant_street (restaurant_id, street_id) values (3,5);
insert into restaurant_street (restaurant_id, street_id) values (3,6);
insert into restaurant_street (restaurant_id, street_id) values (3,7);
insert into restaurant_street (restaurant_id, street_id) values (4,8);
insert into restaurant_street (restaurant_id, street_id) values (4,1);
insert into restaurant_street (restaurant_id, street_id) values (4,2);
insert into restaurant_street (restaurant_id, street_id) values (4,14);
insert into restaurant_street (restaurant_id, street_id) values (5,2);
insert into restaurant_street (restaurant_id, street_id) values (5,3);

insert into menu_item (name, price, category, description, available, restaurant_id) values ('Pizza', '28.61', 'OBIADY', 'orci luctus et ultrices posuere cubilia curae duis faucibus accumsan odio curabitur convallis duis consequat dui nec nisi volutpat eleifend', true, 4);
insert into menu_item (name, price, category, description, available, restaurant_id) values ('Kebab', '16.13', 'OBIADY', 'varius ut blandit non interdum in ante vestibulum ante ipsum primis', true, 2);
insert into menu_item (name, price, category, description, available, restaurant_id) values ('Kotelt', '34.56', 'OBIADY', 'aliquam erat volutpat in congue etiam justo etiam pretium iaculis justo in hac', true , 5);
insert into menu_item (name, price, category, description, available, restaurant_id) values ('Frytki', '7.50', 'DODATKI', 'posuere cubilia curae duis faucibus accumsan odio curabitur convallis duis',true , 3);
insert into menu_item (name, price, category, description, available, restaurant_id) values ('Chleb', '29.25', 'DODATKI', 'vel accumsan tellus nisi eu orci mauris lacinia sapien quis',true , 1);
insert into menu_item (name, price, category, description, available, restaurant_id) values ('Falafel', '39.32', 'OBIADY', 'leo odio porttitor id consequat in consequat ut nulla sed accumsan felis ut at dolor', true, 5);
insert into menu_item (name, price, category, description, available, restaurant_id) values ('Ryba', '38.37', 'OBIADY', 'sapien urna pretium nisl ut volutpat sapien arcu sed augue', true, 5);
insert into menu_item (name, price, category, description, available, restaurant_id) values ('Kurczak', '26.79', 'OBIADY', 'luctus et ultrices posuere cubilia curae mauris viverra diam vitae quam', true, 4);
insert into menu_item (name, price, category, description, available, restaurant_id) values ('Wiśnie', '26.23', 'PRZEKĄSKI', 'ipsum dolor sit amet consectetuer adipiscing elit proin risus praesent lectus vestibulum quam sapien varius ut blandit',true, 5);
insert into menu_item (name, price, category, description, available, restaurant_id) values ('Tort', '11.26', 'DESERY', 'neque libero convallis eget eleifend luctus ultricies eu nibh quisque id justo sit amet sapien dignissim',true, 5);
insert into menu_item (name, price, category, description, available, restaurant_id) values ('Kanapka tuńczyk','11.29', 'PRZEKĄSKI','amet turpis elementum ligula vehicula consequat morbi a ipsum integer a nibh in quis justo maecenas',true, 2);
insert into menu_item (name, price, category, description, available, restaurant_id) values ('Piwo', '8.84', 'NAPOJE', 'ac tellus semper interdum mauris ullamcorper purus sit amet nulla quisque arcu libero rutrum ac lobortis vel',true, 5);
insert into menu_item (name, price, category, description, available, restaurant_id) values ('Pierogi', '24.63', 'OBIADY', 'metus arcu adipiscing molestie hendrerit at vulputate vitae nisl aenean lectus pellentesque eget nunc donec quis orci eget orci vehicula',true, 1);
insert into menu_item (name, price, category, description, available, restaurant_id) values ('Kopytka', '38.87', 'DODATKI', 'bibendum felis sed interdum venenatis turpis enim blandit mi in porttitor pede justo eu',true, 1);
insert into menu_item (name, price, category, description, available, restaurant_id) values ('Ziemniaki', '28.64', 'DODATKI', 'pede justo lacinia eget tincidunt eget tempus vel pede morbi porttitor lorem id ligula suspendisse ornare',true, 1);
insert into menu_item (name, price, category, description, available, restaurant_id) values ('Pomidorowa', '17.47', 'ZUPY', 'lacinia eget tincidunt eget tempus vel pede morbi porttitor lorem id',true, 1);
insert into menu_item (name, price, category, description, available, restaurant_id) values ('Rosół', '17.29', 'ZUPY', 'felis donec semper sapien a libero nam dui proin leo odio porttitor id consequat in consequat',true, 4);
insert into menu_item (name, price, category, description, available, restaurant_id) values ('Herbata', '15.00', 'NAPOJE', 'proin at turpis a pede posuere nonummy integer non velit donec diam neque vestibulum eget vulputate',true, 3);
insert into menu_item (name, price, category, description, available, restaurant_id) values ('Zapiekanka', '35.03', 'PRZEKĄSKI', 'tortor duis mattis egestas metus aenean fermentum donec ut mauris eget massa tempor convallis nulla neque',true, 1);
insert into menu_item (name, price, category, description, available, restaurant_id) values ('Ser', '11.23', 'DODATKI', 'mauris sit amet eros suspendisse accumsan tortor quis turpis sed ante vivamus tortor duis mattis egestas metus',true, 1);

insert into orders (orders_number, received_date_time, completed_date_time, cancelled, completed, total_value, customer_id, address_id, restaurant_id) values ('2023.6.28-13.5.27.89', '2021-10-01 14:00:00+02', null, false, false, '33.44', 1, 1, 1);
insert into orders (orders_number, received_date_time, completed_date_time, cancelled, completed, total_value, customer_id, address_id, restaurant_id) values ('2023.6.28-13.5.27.88', '2021-10-01 14:00:00+02', null, false, false, '33.44', 1, 1, 1);
insert into orders (orders_number, received_date_time, completed_date_time, cancelled, completed, total_value, customer_id, address_id, restaurant_id) values ('2023.6.27-13.5.27.87', '2021-10-01 14:00:00+02', null, false, false, '33.44', 2, 1, 1);
insert into orders (orders_number, received_date_time, completed_date_time, cancelled, completed, total_value, customer_id, address_id, restaurant_id) values ('2023.6.21-13.5.27.86', '2021-10-01 14:00:00+02', null, false, false, '33.44', 1, 1, 1);
insert into orders (orders_number, received_date_time, completed_date_time, cancelled, completed, total_value, customer_id, address_id, restaurant_id) values ('2023.6.22-13.5.27.85', '2022-10-01 14:00:00+02', null, false, false, '33.44', 1, 5, 1);
insert into orders (orders_number, received_date_time, completed_date_time, cancelled, completed, total_value, customer_id, address_id, restaurant_id) values ('2023.3.28-13.5.27.84', '2021-10-01 14:00:00+02', '2025-10-01 14:00:00+02', false, true, '33.44', 1, 4, 1);
insert into orders (orders_number, received_date_time, completed_date_time, cancelled, completed, total_value, customer_id, address_id, restaurant_id) values ('2023.6.28-12.5.25.83', '2021-10-01 14:00:00+02', null, false, false, '33.44', 5, 5, 1);
insert into orders (orders_number, received_date_time, completed_date_time, cancelled, completed, total_value, customer_id, address_id, restaurant_id) values ('2023.6.28-13.5.27.61', '2021-10-01 14:00:00+02', null, false, false, '33.44', 1, 5, 1);
insert into orders (orders_number, received_date_time, completed_date_time, cancelled, completed, total_value, customer_id, address_id, restaurant_id) values ('2023.6.28-11.5.27.52', '2021-10-01 14:00:00+02', '2025-10-01 14:00:00+02', false, true, '33.44', 4, 1, 1);
insert into orders (orders_number, received_date_time, completed_date_time, cancelled, completed, total_value, customer_id, address_id, restaurant_id) values ('2023.6.28-13.12.27.22', '2021-10-01 14:00:00+02', null, false, false, '33.44', 1, 3, 1);

insert into menu_item_orders (quantity, menu_item_id, orders_id) values (1, 9, 8);
insert into menu_item_orders (quantity, menu_item_id, orders_id) values (1, 12, 5);
insert into menu_item_orders (quantity, menu_item_id, orders_id) values (2, 6, 2);
insert into menu_item_orders (quantity, menu_item_id, orders_id) values (5, 4, 6);
insert into menu_item_orders (quantity, menu_item_id, orders_id) values (4, 15, 2);
insert into menu_item_orders (quantity, menu_item_id, orders_id) values (2, 4, 3);
insert into menu_item_orders (quantity, menu_item_id, orders_id) values (4, 8, 5);
insert into menu_item_orders (quantity, menu_item_id, orders_id) values (1, 7, 6);
insert into menu_item_orders (quantity, menu_item_id, orders_id) values (5, 2, 7);
insert into menu_item_orders (quantity, menu_item_id, orders_id) values (2, 11, 6);
insert into menu_item_orders (quantity, menu_item_id, orders_id) values (3, 9, 6);
insert into menu_item_orders (quantity, menu_item_id, orders_id) values (3, 8, 3);
insert into menu_item_orders (quantity, menu_item_id, orders_id) values (1, 11, 5);
insert into menu_item_orders (quantity, menu_item_id, orders_id) values (4, 2, 8);
insert into menu_item_orders (quantity, menu_item_id, orders_id) values (4, 10, 6);
insert into menu_item_orders (quantity, menu_item_id, orders_id) values (2, 4, 7);
insert into menu_item_orders (quantity, menu_item_id, orders_id) values (1, 3, 3);
insert into menu_item_orders (quantity, menu_item_id, orders_id) values (2, 2, 1);
insert into menu_item_orders (quantity, menu_item_id, orders_id) values (5, 1, 1);
insert into menu_item_orders (quantity, menu_item_id, orders_id) values (2, 13, 7);
insert into menu_item_orders (quantity, menu_item_id, orders_id) values (4, 4, 7);
insert into menu_item_orders (quantity, menu_item_id, orders_id) values (3, 7, 6);
insert into menu_item_orders (quantity, menu_item_id, orders_id) values (3, 3, 3);
insert into menu_item_orders (quantity, menu_item_id, orders_id) values (1, 11, 7);
insert into menu_item_orders (quantity, menu_item_id, orders_id) values (1, 7, 4);





